# -*- coding: utf-8 -*-
# set_workset.py
#
# Assigns every reinforcement element in the model to a chosen workset.

from pyrevit import revit, DB, forms, script
from Autodesk.Revit.DB import FilteredWorksetCollector, WorksetKind
from System.Collections.Generic import List

doc = revit.doc

try:
    from Snippets import _dialogs as sdlg
except Exception:
    sdlg = None

TITLE = "Set Rebar to Workset"

# ── DIALOGS ───────────────────────────────────────────────────────────────────

def _alert(message, title=TITLE, exitscript=False):
    """Themed popup via the shared Snippets dialog lib, falls back to
    pyRevit's default forms.alert if the shared lib isn't available."""
    if sdlg:
        sdlg.message(message, title=title)
    else:
        forms.alert(message, title=title)
    if exitscript:
        script.exit()


def _confirm(message, title=TITLE, no="Cancel"):
    """Themed yes/no popup, returns True on yes."""
    if sdlg:
        return sdlg.confirm(message, title=title, no=no)
    return bool(forms.alert(message, title=title, ok=False, yes=True, no=True))

# ── WORKSHARING GUARD ─────────────────────────────────────────────────────────

# Without this the run falls through to "Create New", Workset.Create throws,
# and the user gets a raw API exception instead of a straight answer.
if not doc.IsWorkshared:
    _alert("This model is not workshared, so it has no worksets to assign "
           "rebar to.\n\nEnable worksharing first.", exitscript=True)

# ── GET WORKSETS ──────────────────────────────────────────────────────────────

worksets       = list(FilteredWorksetCollector(doc)
                      .OfKind(WorksetKind.UserWorkset)
                      .ToWorksets())
rebar_worksets = [ws for ws in worksets if "rebar" in ws.Name.lower()]

# ── FUNCTIONS ─────────────────────────────────────────────────────────────────

def select_or_create_workset():
    """Show all user worksets plus a Create New option."""
    options       = [ws.Name for ws in worksets] + ["Create New"]
    selected_name = forms.SelectFromList.show(
        options, button_name="Select or Create Workset")

    if not selected_name:
        _alert("Operation cancelled.")
        return None

    if selected_name == "Create New":
        new_name = forms.ask_for_string(
            prompt="Enter name for new Rebar workset:",
            default="Rebar"
        )
        if not new_name:
            _alert("Invalid name. Operation cancelled.")
            return None

        # Built before the try so the except block can always ask whether it
        # started -- a throwing constructor used to raise UnboundLocalError
        # here and mask the real error.
        transaction = DB.Transaction(doc, "Create Rebar Workset")
        try:
            transaction.Start()
            new_ws = DB.Workset.Create(doc, new_name)
            transaction.Commit()
            return new_ws
        except Exception as e:
            if transaction.HasStarted():
                transaction.RollBack()
            _alert("Failed to create workset: {}".format(str(e)))
            return None

    return next(ws for ws in worksets if ws.Name == selected_name)


def get_target_workset():
    """Determine which workset to use based on what already exists."""
    num_rebar = len(rebar_worksets)

    if num_rebar == 1:
        return rebar_worksets[0]

    if num_rebar > 1:
        options       = [ws.Name for ws in rebar_worksets] + ["Other"]
        selected_name = forms.SelectFromList.show(
            options, button_name="Select Rebar Workset")
        if not selected_name:
            _alert("Operation cancelled.")
            return None
        if selected_name == "Other":
            return select_or_create_workset()
        return next(ws for ws in rebar_worksets if ws.Name == selected_name)

    # No rebar worksets found, go straight to full list
    return select_or_create_workset()


def collect_reinforcement():
    """Return every reinforcement element in the model.

    OfClass(Rebar) only sees free-standing bars: rebar generated by Area and
    Path Reinforcement is RebarInSystem, fabric is different again, and none
    of those are Rebar subclasses, so a class filter left most of the
    reinforcement behind. Filtering by category picks all of it up -- the
    read-only check below then skips system-owned bars, whose workset follows
    their parent and cannot be set directly.
    """
    category_names = [
        "OST_Rebar",
        "OST_AreaRein",
        "OST_PathRein",
        "OST_FabricAreas",
        "OST_FabricReinforcement",
    ]
    categories = List[DB.BuiltInCategory]()
    for name in category_names:
        bic = getattr(DB.BuiltInCategory, name, None)
        if bic is not None:
            categories.Add(bic)

    return list(
        DB.FilteredElementCollector(doc)
          .WherePasses(DB.ElementMulticategoryFilter(categories))
          .WhereElementIsNotElementType()
    )

# ── GET TARGET WORKSET ────────────────────────────────────────────────────────

target_ws = get_target_workset()
if not target_ws:
    script.exit()

# ── COLLECT REINFORCEMENT ─────────────────────────────────────────────────────

rebar_elements = collect_reinforcement()

if not rebar_elements:
    _alert("No reinforcement elements found in the model.", exitscript=True)

if not _confirm(
        "Move {} reinforcement element(s) to \"{}\"?".format(
            len(rebar_elements), target_ws.Name),
        no="Cancel"):
    script.exit()

# ── SET WORKSET ───────────────────────────────────────────────────────────────

# WorksetId keeps IntegerValue -- only ElementId lost it in Revit 2026.
target_ws_value = target_ws.Id.IntegerValue

moved  = 0
locked = 0   # workset parameter read-only, e.g. bars owned by a rein. system
failed = 0

transaction = DB.Transaction(doc, "Set Rebar to Workset")
transaction.Start()

try:
    for elem in rebar_elements:
        # Handled per element: this tool only ever runs in a workshared model,
        # where a single element owned by another user used to throw and roll
        # back every bar already moved.
        try:
            param = elem.get_Parameter(DB.BuiltInParameter.ELEM_PARTITION_PARAM)
            if param is None or param.IsReadOnly:
                locked += 1
                continue
            if param.Set(target_ws_value):
                moved += 1
            else:
                failed += 1
        except Exception:
            failed += 1
    transaction.Commit()
except Exception as e:
    if transaction.HasStarted():
        transaction.RollBack()
    _alert("Error: {}".format(str(e)), exitscript=True)

# ── REPORT ────────────────────────────────────────────────────────────────────

summary = ["Moved {} element(s) to \"{}\" workset.".format(
    moved, target_ws.Name)]
if locked:
    summary.append(
        "{} skipped - workset is read-only. Bars belonging to an Area or "
        "Path Reinforcement system follow their parent's workset.".format(
            locked))
if failed:
    summary.append(
        "{} could not be changed - most likely owned by another user.".format(
            failed))

_alert("\n\n".join(summary))
